version: 2

models:
  - name: fact_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_id

  - name: fact_order_reviews
    columns:
      - name: review_id
        tests: [not_null, unique]
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_id

  - name: fact_order_payments
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fact_orders')
              field: order_id