FROM bitnami/spark:3.5.1

USER root

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/bitnami/spark/jars_extra

RUN curl -L -o /opt/bitnami/spark/jars_extra/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar

RUN curl -L -o /opt/bitnami/spark/jars_extra/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar


ENV SPARK_EXTRA_CLASSPATH="/opt/bitnami/spark/jars_extra/*"

WORKDIR /workspace

USER 1001
