FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir pip==24.0 \
  && pip install --no-cache-dir dbt-redshift==1.10.1

ENV DBT_PROFILES_DIR=/root/.dbt

CMD ["bash", "-lc", "sleep infinity"]